id: 19ac153201214df089033354ce838b6f
initial_creation_type: ocr
source_metadata:
  volumes:
    228efff8640845099de88e6aef4e665d:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དགེ་བའི་འདོད་འཇོ།
      total_pages: 1044
      volume_number: 38
